server:
  port: 1003

spring:
  application:
    name: auth-service

  datasource:
    url: jdbc:postgresql://localhost:5432/ecommerce?characterEncoding=UTF-8&serverTimezone=UTC
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    database: Postgresql
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

eureka:
  client:
    service-url:
      defaultZone: http://localhost:1000/eureka/

mybatis:
  mapper-locations: classpath:mapper/**/*.xml
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

app:
  jwt:
    secret: 8ae2a6ebc0cd16aecb0e94e85c1eed0a1b1d8a668f65c3838b341a99197ff370
    refresh-secret: 9ae2a6ebc0cd16aecb0e94e85c1eed0a1b1d8a668f65c3838b341a99197ff371
  jwt-expiration-milliseconds: 1800000
  refresh-token-expiration-milliseconds: 3600000