spring.application.name=spring6-auth
server.port=1000

spring.profiles.active=h2

#spring doc
springdoc.show-actuator=true
springdoc.api-docs.enabled=true
springdoc.enable-spring-security=true

##spring security
#spring.security.enabled=false
#spring.security.account.name=account
#spring.security.account.password=pass

#CORS
cors.allowed.origins=http://localhost:4200,http://localhost:4201
cors.allowed.methods=GET,POST,PUT,DELETE,PATCH,OPTIONS



#file upload
## MULTIPART (MultipartProperties)
# Enable multipart uploads
spring.servlet.multipart.enabled=true
# Threshold after which files are written to disk.
spring.servlet.multipart.file-size-threshold=2KB
# Max file size.
spring.servlet.multipart.max-file-size=200MB
# Max Request Size
spring.servlet.multipart.max-request-size=215MB
## File Storage Properties
# All files uploaded through the REST API will be stored in this directory

#devtools
spring.devtools.livereload.enabled=true
spring.devtools.livereload.port=35729
spring.devtools.remote.restart.enabled=true
spring.devtools.restart.enabled=true


#!important - Do not use it in PROD
logging.level.com.pm.spring.ema.auth=debug
logging.level.org.springframework.security.web.FilterChainProxy=DEBUG

# Hibernate envers
spring.jpa.properties.org.hibernate.envers.audit_table_suffix=_AUDIT
spring.jpa.properties.org.hibernate.envers.revision_field_name=revision
spring.jpa.properties.org.hibernate.envers.revision_type_field_name=revision_type
spring.jpa.properties.org.hibernate.envers.store_data_at_delete=true

# Time zone
spring.jackson.time-zone=UTC
rest.api.response.time-zone=Asia/Kolkata


# JWT
application.security.jwt.secret-key=w2KgKVQQhW4wFpa4rijsLcLm2uZS25PtuMZYvqiDFlf0wUBj
application.security.jwt.expiration.minutes=20
application.security.jwt.refresh-token.expiration.hours=24


application.auth.url=/api/v1/auth





