spring.application.name=spring6-ecommerce-user
server.port=1002
spring.profiles.active=h2
logging.level.com.spring6.ecommerce=debug
springdoc.show-actuator=true
springdoc.api-docs.enabled=true


springdoc.enable-spring-security=false
security


