DROP DATABASE IF EXISTS ecommerce_db;
DROP USER IF EXISTS `ecommerce_user`@`%`;
CREATE DATABASE IF NOT EXISTS ecommerce_db CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE USER IF NOT EXISTS `ecommerce_user`@`%` IDENTIFIED WITH mysql_native_password BY 'ecommerce_password';
GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, DROP, REFERENCES, INDEX, ALTER, EXECUTE, CREATE VIEW, SHOW VIEW,
    CREATE ROUTINE, ALTER ROUTINE, EVENT, TRIGGER ON `ecommerce_db`.* TO `ecommerce_user`@`%`;