# Brand API
###
GET {{url}}1001/order/list
Accept: application/json

###

# curl --location 'http://localhost:1001/order/page/1?sortField=name&sortDir=asc&keyword=s'
#--header 'accept: */*'
GET http://localhost:1001/order/page/1?sortField=name&sortDir=asc&keyword=s
accept: */*

###
GET http://localhost:1001/order/page/1?sortField=name&sortDir=asc&keyword=
accept: */*
###
GET http://localhost:1001/order/page/2?sortField=name&sortDir=asc&keyword=
accept: */*
###
POST {{url}}1001/order/create
Content-Type: application/json
{
  "name": "Ma",
  "logo": "Mac.png"
}

# Category API

###

GET {{url}}1000/subCategory/list
Accept: application/json

# Product API
###
GET localhost:1002/product/list
Accept: application/json

###
GET localhost:1002/product/getById/9ed12106-6a66-4036-9c76-2700f4391249
Accept: application/json

###
POST http://localhost:1002/product/addProduct
Content-Type: application/json

{
  "name": "Note 11",
  "alias": "A400",
  "shortDescription": "String",
  "fullDescription": "String",
  "inStock": true,
  "cost":12569.0 ,
  "price": 12000,
  "length": 1.2,
  "width": 1.5,
  "height": 5.9,
  "weight": 22,
  "categoryId": "3540536f-5468-42d4-92ff-9a576c3e7747",
  "brandId": "a3976462-93b7-4303-b504-0e5b0eddb283",
  "enabled": true
}


###
PUT http://localhost:1002/product/update/bb4ff010-fade-41ee-b49b-d1bda72a82bc/enabled/false
Accept: application/json

###
DELETE http://localhost:1002/product/delete/bb4ff010-fade-41ee-b49b-d1bda72a82bc

###
POST https://api.brevo.com/v3/smtp/email
Content-Type: application/json
api-key: ${API_KEY}

{
  "sender": {
    "name": "EMS App",
    "email": "v4431365@gmail.com"
  },
  "to": [
    {
      "email": "rvkrishna13052001@gmail.com",
      "name": "Venkata Krishna Repalle"
    }
  ],
  "subject": "My subject",
  "htmlContent": "Congratulations! You successfully sent this example email via the Brevo API."
}

###
POST http://localhost:8080/realms/ecommerce/protocol/openid-connect/token
Content-Type: application/x-www-form-urlencoded

grant_type=client_credentials&client_id=${CLIENT_ID}&client_secret=${CLIENT_SECRET}