# Brand API
###
GET {{url}}1001/brand/list
Accept: application/json

###

# curl --location 'http://localhost:1001/brand/page/1?sortField=name&sortDir=asc&keyword=s'
#--header 'accept: */*'
GET http://localhost:1001/brand/page/1?sortField=name&sortDir=asc&keyword=s
accept: */*

###
GET http://localhost:1001/brand/page/1?sortField=name&sortDir=asc&keyword=
accept: */*
###
GET http://localhost:1001/brand/page/2?sortField=name&sortDir=asc&keyword=
accept: */*
###
POST {{url}}1001/brand/create
Content-Type: application/json
{
  "name": "Ma",
  "logo": "Mac.png"
}

# Category API

###

GET {{url}}1000/category/list
Accept: application/json

# Product API