###
# curl -X 'POST'
#  'http://localhost:1000/api/v1/auth/authenticate'
#  -H 'accept: */*'
#  -H 'Content-Type: application/json'
#  -d '{
#  "username": "root",
#  "password": "root"
#}'
POST http://localhost:1000/api/v1/auth/authenticate
accept: */*
Content-Type: application/json

{
  "username": "root",
  "password": "root"
}

###



