spring.application.name=spring6-brand
server.port=1001
spring.profiles.active=h2
logging.level.com.spring6.ecommerce=debug
springdoc.show-actuator=true
springdoc.api-docs.enabled=true

#file upload
## MULTIPART (MultipartProperties)
# Enable multipart uploads
spring.servlet.multipart.enabled=true
# Threshold after which files are written to disk.
spring.servlet.multipart.file-size-threshold=2KB
# Max file size.
spring.servlet.multipart.max-file-size=200MB
# Max Request Size
spring.servlet.multipart.max-request-size=215MB

## File Storage Properties
# All files uploaded through the REST API will be stored in this directory
file.upload-directory=spring6-ecommerce-brand/brand-logos/

#Devtools
spring.devtools.restart.enabled=true

spring.messages.basename=messages
spring.messages.encoding=UTF-8


