log:
  appName: mail-service

logging:
  level:
    org:
      springframework:
        cloud: DEBUG
server:
  port: 1004

spring:
  mail:
    host: smtp.gmail.com
    username: v4431365@gmail.com
    password: iponuhntztqltauh
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  cloud:
    config:
      import-check:
        enabled: false

default:
  send:
    email:
      address: v4431365@gmail.com
      header: Chat App OTP Verification


email:
  template:
    login: send-login-otp
    forgot-password: send-forgot-password-otp