#todo : remove this file
##Email Properties
default.send.email=v4431365@gmail.com
default.send.email.header=Chat App OTP Verification

##
email.template.login=send-login-otp
email.template.forgot-password= send-forgot-password-otp