spring.application.name=spring6-ecommerce-category
server.port=1000

spring.profiles.active=h2
logging.level.com.spring6.ecommerce=debug

springdoc.show-actuator=true
springdoc.api-docs.enabled=false

#http://localhost:8080/h2-console



