server:
  port: 1006
spring:
  application:
    name: brand-service
  datasource:
    url: jdbc:postgresql://localhost:5432/ecommerce?characterEncoding=UTF-8&serverTimezone=UTC
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    database: Postgresql
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

  cloud:
    config:
      import-check:
        enabled: false

eureka:
  client:
    service-url:
      defaultZone: http://localhost:1000/eureka/
  instance:
    prefer-ip-address: true

app:
  jwt:
    secret: 8ae2a6ebc0cd16aecb0e94e85c1eed0a1b1d8a668f65c3838b341a99197ff370
  jwt-expiration-milliseconds: 1800000

file:
  upload_directory: spring6-ecommerce-brand/brand-logos