version: '3.9'

volumes:
  postgres:
    driver: local

services:
  postgres:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-changeme}
      POSTGRES_DB: ${POSTGRES_DB:-postgres}
    volumes:
      - postgres:/data/postgres
      - ./data:/var/lib/postgresql/data
      - ./postgresql.conf:/etc/postgres/sql/postgresql.conf
    ports:
      - "5432:5432"
  keycloak:
    image: quay.io/keycloak/keycloak:${KEYCLOAK_VERSION:-latest}
    container_name: keycloak
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: ${POSTGRES_DB:-postgres}
      #      KC_DB_URL: jdbc:postgresql://localhost/keycloak
      KC_DB_URL: jdbc:postgresql://postgres/${POSTGRES_DB:-postgres}
      KC_DB_USERNAME: ${POSTGRES_USER:-postgres}
      KC_DB_PASSWORD: ${POSTGRES_PASSWORD:-changeme}
      KC_HOSTNAME: localhost
      KC_HEALTH_ENABLED: true
      KC_METRICS_ENABLED: true
    ports:
      - "9090:8080"
    command:
      - start-dev
    depends_on:
      - postgres