# Access token

# curl --location 'http://localhost:8081/auth/realms/chat_app/protocol/openid-connect/token'
#--header 'Content-Type: application/x-www-form-urlencoded'
#--data-urlencode 'client_id=spring-chat-application'
#--data-urlencode 'username=user1'
#--data-urlencode 'password=user1pass'
#--data-urlencode 'grant_type=password'

POST http://localhost:8081/auth/realms/chat_app/protocol/openid-connect/token
Content-Type: application/x-www-form-urlencoded

client_id=spring-chat-application&username=user1&password=user1pass&grant_type=password

###
# Refresh token

# curl --location 'http://localhost:8081/auth/realms/chat_app/protocol/openid-connect/token'
#--header 'Content-Type: application/x-www-form-urlencoded'
#--header 'Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJjM2NmNjI0Mi1mMzA4LTRjYWItOTY5Ny04ZTljZDlhNWQ2YTkifQ.eyJleHAiOjE3MDE0MTEyOTUsImlhdCI6MTcwMTQwOTQ5NSwianRpIjoiZWQ5OTZjYjctMjVmOC00NmIyLThmYWYtZWIwOTY3ZjdmYmE5IiwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDo4MDgxL2F1dGgvcmVhbG1zL2NoYXRfYXBwIiwiYXVkIjoiaHR0cDovL2xvY2FsaG9zdDo4MDgxL2F1dGgvcmVhbG1zL2NoYXRfYXBwIiwic3ViIjoiOTlhYzZlYWEtNTAxOC00YzA2LWJmMTItNDJlMGE0NDc1YTQ2IiwidHlwIjoiUmVmcmVzaCIsImF6cCI6InNwcmluZy1jaGF0LWFwcGxpY2F0aW9uIiwic2Vzc2lvbl9zdGF0ZSI6IjQ0OWJmYThhLWU5NTEtNGMyYi1iMDUxLWM2NWE4OWQwNjdhMCIsInNjb3BlIjoiZW1haWwgcHJvZmlsZSJ9.clzW8k8hT9-1KmrRYwCiz0Hu0GnC1h6r-xO7_NOkxu4'
#--data-urlencode 'client_id=spring-chat-application'
#--data-urlencode 'refresh_token=eyJhbGciOiJIUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJjM2NmNjI0Mi1mMzA4LTRjYWItOTY5Ny04ZTljZDlhNWQ2YTkifQ.eyJleHAiOjE3MDE0MTEyOTUsImlhdCI6MTcwMTQwOTQ5NSwianRpIjoiZWQ5OTZjYjctMjVmOC00NmIyLThmYWYtZWIwOTY3ZjdmYmE5IiwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDo4MDgxL2F1dGgvcmVhbG1zL2NoYXRfYXBwIiwiYXVkIjoiaHR0cDovL2xvY2FsaG9zdDo4MDgxL2F1dGgvcmVhbG1zL2NoYXRfYXBwIiwic3ViIjoiOTlhYzZlYWEtNTAxOC00YzA2LWJmMTItNDJlMGE0NDc1YTQ2IiwidHlwIjoiUmVmcmVzaCIsImF6cCI6InNwcmluZy1jaGF0LWFwcGxpY2F0aW9uIiwic2Vzc2lvbl9zdGF0ZSI6IjQ0OWJmYThhLWU5NTEtNGMyYi1iMDUxLWM2NWE4OWQwNjdhMCIsInNjb3BlIjoiZW1haWwgcHJvZmlsZSJ9.clzW8k8hT9-1KmrRYwCiz0Hu0GnC1h6r-xO7_NOkxu4'
#--data-urlencode 'grant_type=refresh_token'

POST http://localhost:8081/auth/realms/chat_app/protocol/openid-connect/token
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJjM2NmNjI0Mi1mMzA4LTRjYWItOTY5Ny04ZTljZDlhNWQ2YTkifQ.eyJleHAiOjE3MDE0MTEyOTUsImlhdCI6MTcwMTQwOTQ5NSwianRpIjoiZWQ5OTZjYjctMjVmOC00NmIyLThmYWYtZWIwOTY3ZjdmYmE5IiwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDo4MDgxL2F1dGgvcmVhbG1zL2NoYXRfYXBwIiwiYXVkIjoiaHR0cDovL2xvY2FsaG9zdDo4MDgxL2F1dGgvcmVhbG1zL2NoYXRfYXBwIiwic3ViIjoiOTlhYzZlYWEtNTAxOC00YzA2LWJmMTItNDJlMGE0NDc1YTQ2IiwidHlwIjoiUmVmcmVzaCIsImF6cCI6InNwcmluZy1jaGF0LWFwcGxpY2F0aW9uIiwic2Vzc2lvbl9zdGF0ZSI6IjQ0OWJmYThhLWU5NTEtNGMyYi1iMDUxLWM2NWE4OWQwNjdhMCIsInNjb3BlIjoiZW1haWwgcHJvZmlsZSJ9.clzW8k8hT9-1KmrRYwCiz0Hu0GnC1h6r-xO7_NOkxu4
Content-Type: application/x-www-form-urlencoded

client_id=spring-chat-application&grant_type=refresh_token&refresh_token=eyJhbGciOiJIUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJjM2NmNjI0Mi1mMzA4LTRjYWItOTY5Ny04ZTljZDlhNWQ2YTkifQ.eyJleHAiOjE3MDE0MTEyOTUsImlhdCI6MTcwMTQwOTQ5NSwianRpIjoiZWQ5OTZjYjctMjVmOC00NmIyLThmYWYtZWIwOTY3ZjdmYmE5IiwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDo4MDgxL2F1dGgvcmVhbG1zL2NoYXRfYXBwIiwiYXVkIjoiaHR0cDovL2xvY2FsaG9zdDo4MDgxL2F1dGgvcmVhbG1zL2NoYXRfYXBwIiwic3ViIjoiOTlhYzZlYWEtNTAxOC00YzA2LWJmMTItNDJlMGE0NDc1YTQ2IiwidHlwIjoiUmVmcmVzaCIsImF6cCI6InNwcmluZy1jaGF0LWFwcGxpY2F0aW9uIiwic2Vzc2lvbl9zdGF0ZSI6IjQ0OWJmYThhLWU5NTEtNGMyYi1iMDUxLWM2NWE4OWQwNjdhMCIsInNjb3BlIjoiZW1haWwgcHJvZmlsZSJ9.clzW8k8hT9-1KmrRYwCiz0Hu0GnC1h6r-xO7_NOkxu4

###
#openid-configuration

# curl --location 'http://localhost:8081/auth/realms/chat_app_realm/.well-known/openid-configuration'

GET http://localhost:8081/auth/realms/chat_app_realm/.well-known/openid-configuration

###


