version: '3.9'

services:
  config-server:
    build:
      context: ./../config-server
      dockerfile: Dockerfile
      args:
        - ARTIFACT_ID=config-server
        - VERSION=${SERVICE_VERSION:-latest}
    container_name: config-server
    image: ${GROUP_ID}/config.server:${SERVICE_VERSION:-latest}
    ports:
      - "8888:8888"
      - "5007:5007"
    volumes:
      - "./docker-logs:/workspace/config-server/logs"
    environment:
      - "JAVA_OPTS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:8888 -Xms128m -Xmx256m"
      - "LOG_APP-NAME=config-server"
      - "SERVER_PORT=8888"
      - "CHAT_ENCRYPT_KEY=${CHAT_ENCRYPT_KEY}"
      - "MANAGEMENT_ZIPKIN_TRACING_ENDPOINT=http://zipkin:9411"
    networks:
      - ${GLOBAL_NETWORK:-services}
  config-server-ha:
    build:
      context: ./../config-server
      dockerfile: Dockerfile
      args:
        - ARTIFACT_ID=config-server
        - VERSION=${SERVICE_VERSION:-latest}
    image: ${GROUP_ID}/config.server:${SERVICE_VERSION:-latest}
    ports:
      - "5018:5018"
      - "8889:8889"
    volumes:
      - "./docker-logs:/workspace/config-server/logs"
    environment:
      - "JAVA_OPTS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5018 -Xms128m -Xmx256m"
      - "LOG_APP-NAME=config-server-ha"
      - "SERVER_PORT=8889"
      - "CHAT_ENCRYPT_KEY=${CHAT_ENCRYPT_KEY}"
      - "MANAGEMENT_ZIPKIN_TRACING_ENDPOINT=http://zipkin:9411"
    networks:
      - ${GLOBAL_NETWORK:-services}