version: '3.9'

services:
  config-server:
    build:
      context: ./../config-server
      dockerfile: Dockerfile
      args:
        - ARTIFACT_ID=config-server
        - VERSION=${SERVICE_VERSION:-latest}
    container_name: config-server
    image: ${GROUP_ID}/config.server:${SERVICE_VERSION:-latest}
    ports:
      - "8888:8888"
      - "5007:5007"
    volumes:
      - "./docker-logs:/workspace/config-server/logs"
    environment:
      - "JAVA_OPTS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:8888 -Xms128m -Xmx256m"
      - "LOG_APP-NAME=config-server"
      - "SERVER_PORT=8888"
      - "CHAT_ENCRYPT_KEY=${CHAT_ENCRYPT_KEY}"
      - "MANAGEMENT_ZIPKIN_TRACING_ENDPOINT=http://zipkin:9411"
    networks:
      - ${GLOBAL_NETWORK:-services}
  config-server-ha:
    build:
      context: ./../config-server
      dockerfile: Dockerfile
      args:
        - ARTIFACT_ID=config-server
        - VERSION=${SERVICE_VERSION:-latest}
    image: ${GROUP_ID}/config.server:${SERVICE_VERSION:-latest}
    ports:
      - "5018:5018"
      - "8889:8889"
    volumes:
      - "./docker-logs:/workspace/config-server/logs"
    environment:
      - "JAVA_OPTS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5018 -Xms128m -Xmx256m"
      - "LOG_APP-NAME=config-server-ha"
      - "SERVER_PORT=8889"
      - "CHAT_ENCRYPT_KEY=${CHAT_ENCRYPT_KEY}"
      - "MANAGEMENT_ZIPKIN_TRACING_ENDPOINT=http://zipkin:9411"
    networks:
      - ${GLOBAL_NETWORK:-services}
  discovery-service-1:
    build:
      context: ./../discovery-service
      dockerfile: Dockerfile
      args:
        - ARTIFACT_ID=discovery-service
        - VERSION=${SERVICE_VERSION:-latest}
    image: ${GROUP_ID}/discovery.service:${SERVICE_VERSION:-latest}
    ports:
      - "5014:5014"
      - "8761:8761"
    volumes:
      - "./docker-logs:/workspace/discovery-service/logs"
    environment:
      - "JAVA_OPTS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5014 -Xms128m -Xmx256m"
      - "LOGGING_LEVEL_ROOT=info"
      - "SERVER_PORT=8761"
      - "SPRING_PROFILES_ACTIVE=peer1"
      - "EUREKA_INSTANCE_HOSTNAME=discovery-service-1"
      - "LOG_APP-NAME=discovery-service-1"
      - "MANAGEMENT_ZIPKIN_TRACING_ENDPOINT=http://zipkin:9411"
    networks:
      - ${GLOBAL_NETWORK:-services}
  discovery-service-2:
    build:
      context: ./../discovery-service
      dockerfile: Dockerfile
      args:
        - ARTIFACT_ID=discovery-service
        - VERSION=${SERVICE_VERSION:-latest}
    image: ${GROUP_ID}/discovery.service:${SERVICE_VERSION:-latest}
    ports:
      - "5015:5015"
      - "8762:8762"
    volumes:
      - "./docker-logs:/workspace/discovery-service/logs"
    environment:
      - "JAVA_OPTS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5015 -Xms128m -Xmx256m"
      - "LOGGING_LEVEL_ROOT=info"
      - "SERVER_PORT=8762"
      - "SPRING_PROFILES_ACTIVE=peer2"
      - "EUREKA_INSTANCE_HOSTNAME=discovery-service-2"
      - "LOG_APP-NAME=discovery-service-2"
      - "MANAGEMENT_ZIPKIN_TRACING_ENDPOINT=http://zipkin:9411"
    networks:
      - ${GLOBAL_NETWORK:-services}
  authentication-service:
    build:
      context: ./../authentication-service
      dockerfile: Dockerfile
      args:
        - ARTIFACT_ID=authentication-service
        - VERSION=${SERVICE_VERSION:-latest}
    container_name: authentication-service
    image: ${GROUP_ID}/authentication.service:${SERVICE_VERSION:-latest}
    ports:
      - "5013:5013"
      - "1001:1001"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://config-server:8888/actuator/health" ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s
    volumes:
      - "./docker-logs:/workspace/authentication-service/logs"
    depends_on:
      - config-server
      - postgres-db
    environment:
      - "JAVA_OPTS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5013 -Xms128m -Xmx256m"
      - "LOG_APP-NAME=authentication-service"
      - "SERVER_PORT=1001"
      - "SERVER_SERVLET_CONTEXT-PATH=/"
      - "CHAT_ENCRYPT_KEY=${CHAT_ENCRYPT_KEY}"
      - "MANAGEMENT_ZIPKIN_TRACING_ENDPOINT=http://zipkin:9411"
      - "SPRING_DATASOURCE_URL=jdbc:postgresql://host.docker.internal:5432/postgres?currentSchema=public&binaryTransfer=true&reWriteBatchedInserts=true"
      - "SPRING_CLOUD_CONFIG_URI=http://config-server:8888"
      - "EUREKA_CLIENT_SERVICE-URL_DEFAULT-ZONE=http://discovery-service-1:8761/eureka/,http://discovery-service-2:8762/eureka/"
    networks:
      - ${GLOBAL_NETWORK:-services}
  message-service:
    build:
      context: ./../message-service
      dockerfile: Dockerfile
      args:
        - ARTIFACT_ID=message-service
        - VERSION=${SERVICE_VERSION:-latest}
    image: ${GROUP_ID}/message.service:${SERVICE_VERSION:-latest}
    ports:
      - "1000:1000"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://config-server:8888/actuator/health" ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s
    volumes:
      - "./docker-logs:/workspace/message-service/logs"
    depends_on:
      - config-server
      - postgres-db
    environment:
      - "JAVA_OPTS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:1000 -Xms128m -Xmx256m"
      - "LOG_APP-NAME=message-service"
      - "SERVER_PORT=1000"
      - "CHAT_ENCRYPT_KEY=${CHAT_ENCRYPT_KEY}"
      - "MANAGEMENT_ZIPKIN_TRACING_ENDPOINT=http://zipkin:9411"
      - "SERVER_SERVLET_CONTEXT-PATH=/"
      - "SPRING_CLOUD_CONFIG_URI=http://config-server:8888,http://config-server-ha:8889"
      - "SPRING_DATASOURCE_URL=jdbc:postgresql://host.docker.internal:5432/chat_db?currentSchema=public&binaryTransfer=true&reWriteBatchedInserts=true"
      - "SPRING_CLOUD_CONFIG_URI=http://config-server:8888"
      - "EUREKA_CLIENT_SERVICE-URL_DEFAULT-ZONE=http://discovery-service-1:8761/eureka/,http://discovery-service-2:8762/eureka/"
    networks:
      - ${GLOBAL_NETWORK:-services}
  gateway-service-1:
    build:
      context: ./../gateway-service
      dockerfile: Dockerfile
      args:
        - ARTIFACT_ID=gateway-service
        - VERSION=${SERVICE_VERSION:-latest}
    image: ${GROUP_ID}/gateway.service:${SERVICE_VERSION:-latest}
    ports:
      - "5016:5016/tcp"
      - "9092:9092/tcp"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://config-server:8888/actuator/health" ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s
    volumes:
      - "./docker-logs:/workspace/gateway-service/logs"
      - "./check-keycloak-server-started.sh:/workspace/gateway-service/scripts/check-keycloak-server-started.sh"
#    links:
#      - "redis-master:redis"
    environment:
      - "JAVA_OPTS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5016 -Xms128m -Xmx256m"
      - "LOGGING_LEVEL_COM_MICROSERVICES_DEMO=debug"
      - "LOGGING_LEVEL_ROOT=debug"
      - "SERVER_PORT=9092"
      - "SPRING_CLOUD_CONFIG_URI=http://config-server:8888,http://config-server-ha:8889"
      - "SPRING_REDIS_HOST=redis"
      - "LOG_APP-NAME=gateway-service-1"
      - "EUREKA_CLIENT_SERVICE-URL_DEFAULT-ZONE=http://discovery-service-1:8761/eureka/,http://discovery-service-2:8762/eureka/"
      - "CHAT_ENCRYPT_KEY=${CHAT_ENCRYPT_KEY}"
      - "SPRING_ZIPKIN_SENDER_TYPE=kafka"
      - "SPRING_KAFKA_BOOTSTRAP-SERVERS=kafka-broker-1:9092, kafka-broker-2:9092, kafka-broker-3:9092"
      - "SPRING_SLEUTH_SAMPLER_PROBABILITY=1.0"
      - "MANAGEMENT_ZIPKIN_TRACING_ENDPOINT=http://zipkin:9411"
    networks:
      - ${GLOBAL_NETWORK:-services}
  gateway-service-2:
    build:
      context: ./../gateway-service
      dockerfile: Dockerfile
      args:
        - ARTIFACT_ID=gateway-service
        - VERSION=${SERVICE_VERSION:-latest}
    image: ${GROUP_ID}/gateway.service:${SERVICE_VERSION:-latest}
    ports:
      - "5017:5017/tcp"
      - "9093:9093/tcp"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://config-server:8888/actuator/health" ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s
    volumes:
      - "./docker-logs:/workspace/gateway-service/logs"
#      - "./check-keycloak-server-started.sh:/workspace/gateway-service/scripts/check-keycloak-server-started.sh"
#    user: root
#    entrypoint: [ "/workspace/gateway-service/scripts/check-config-server-started.sh" ]
#    links:
#      - "redis-master:redis"
    environment:
      - "JAVA_OPTS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5017 -Xms128m -Xmx256m"
      - "LOGGING_LEVEL_COM_MICROSERVICES_DEMO=debug"
      - "LOGGING_LEVEL_ROOT=debug"
      - "SERVER_PORT=9093"
      - "SPRING_CLOUD_CONFIG_URI=http://config-server:8888,http://config-server-ha:8889"
      - "SPRING_REDIS_HOST=redis"
      - "LOG_APP-NAME=gateway-service-2"
      - "EUREKA_CLIENT_SERVICE-URL_DEFAULT-ZONE=http://discovery-service-1:8761/eureka/,http://discovery-service-2:8762/eureka/"
      - "CHAT_ENCRYPT_KEY=${CHAT_ENCRYPT_KEY}"
      - "SPRING_ZIPKIN_SENDER_TYPE=kafka"
      - "SPRING_KAFKA_BOOTSTRAP-SERVERS=kafka-broker-1:9092, kafka-broker-2:9092, kafka-broker-3:9092"
      - "SPRING_SLEUTH_SAMPLER_PROBABILITY=1.0"
      - "MANAGEMENT_ZIPKIN_TRACING_ENDPOINT=http://zipkin:9411"
    networks:
      - ${GLOBAL_NETWORK:-services}