spring.application.name=spring6-account
server.port=1002

spring.profiles.active=h2
# !important - if dev completed then remove this
logging.level.com.pm.spring.ema.auth=debug

#spring doc
springdoc.show-actuator=true
springdoc.api-docs.enabled=true
springdoc.enable-spring-security=false

#spring security
#spring.security.enabled=false
spring.security.account.name=account
spring.security.account.password=pass
spring.security.csrf.enabled=false




#file upload
## MULTIPART (MultipartProperties)
# Enable multipart uploads
spring.servlet.multipart.enabled=true
# Threshold after which files are written to disk.
spring.servlet.multipart.file-size-threshold=2KB
# Max file size.
spring.servlet.multipart.max-file-size=200MB
# Max Request Size
spring.servlet.multipart.max-request-size=215MB
## File Storage Properties
# All files uploaded through the REST API will be stored in this directory
file.upload-directory=spring6-account/account-photos/




