spring.application.name=spring6-ecommerce-subCategory
server.port=1000
spring.profiles.active=h2
logging.level.com.spring6=debug
springdoc.show-actuator=true
springdoc.api-docs.enabled=true
#http://localhost:8080/h2-console



