spring.application.name=spring6-order
server.port=1001
spring.profiles.active=h2
#logging.level.com.spring6=debug
springdoc.show-actuator=true
springdoc.api-docs.enabled=true

#file upload
## MULTIPART (MultipartProperties)
# Enable multipart uploads
spring.servlet.multipart.enabled=true
# Threshold after which files are written to disk.
spring.servlet.multipart.file-size-threshold=2KB
# Max file size.
spring.servlet.multipart.max-file-size=200MB
# Max Request Size
spring.servlet.multipart.max-request-size=215MB
## File Storage Properties
# All files uploaded through the REST API will be stored in this directory
file.upload_directory=spring6-order/order-logos/

#Devtools
spring.devtools.restart.enabled=false

# Logger
#logging.file.path=C:/Users/praja/IdeaProjects/spring6/spring6-order
#logging.file.name=spring6-order-log.log
#logging.level.root=DEBUG

# Hibernate envers
spring.jpa.properties.org.hibernate.envers.audit_table_suffix=_AUDIT
spring.jpa.properties.org.hibernate.envers.revision_field_name=revision
spring.jpa.properties.org.hibernate.envers.revision_type_field_name=revision_type
spring.jpa.properties.org.hibernate.envers.store_data_at_delete=true
#spring.jpa.properties.hibernate.id.new_generator_mappings=false

# Spring Admin
spring.boot.admin.client.url=http://localhost:8080

# Time zone
spring.jackson.time-zone=UTC
rest.api.response.time-zone=Asia/Kolkata





