server:
  port: 1006

spring:
  application:
    name: product-service
  cloud:
    config:
      import-check:
        enabled: false

eureka:
  client:
    service-url:
      defaultZone: http://localhost:1000/eureka/

log:
  appName: product-service

logging:
  level:
    ROOT: INFO
    org.spring.framework.cloud.config: DEBUG
    org:
      hibernate:
        orm:
          jdbc:
            bind: trace
