spring:
  application:
    name: product-service
  profiles:
    active: product
  config:
    import: 'configserver:'
  cloud:
    config:
      name: product-service,config-client
      username: user
      password: password

log:
  appName: product-service

logging:
  level:
    ROOT: INFO
    org.spring.framework.cloud.config: DEBUG
    org:
      hibernate:
        orm:
          jdbc:
            bind: trace