server:
  port: 1001

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/pandimuneeswaranraja/config-server-repo-ema
          default-label: main
          clone-on-start: true
    fail-fast: true
  security:
    user:
      name: user
      password: '{cipher}2e1042272f3912b3b4d1f97a227e0f437250c7d0810a7c045f88d42a3d6b8ef4'

encrypt:
  key: ${CHAT_ENCRYPT_KEY}

eureka:
  client:
    service-url:
      defaultZone: http://localhost:1000/eureka/

log:
  app-name: config-server

# remove for production
logging:
  level:
    ROOT: INFO
    org.spring.framework.cloud.config: DEBUG