server:
  port: 1005

spring:
  application:
    name: address-service

eureka:
  client:
    service-url:
      defaultZone: http://localhost:1000/eureka/

log:
  appName: address-service

logging:
  level:
    ROOT: INFO
    org.spring.framework.cloud.config: DEBUG
    org:
      hibernate:
        orm:
          jdbc:
            bind: trace