###
# curl -X 'POST'
#  'http://localhost:1000/api/v1/auth/authenticate'
#  -H 'accept: */*'
#  -H 'Content-Type: application/json'
#  -d '{
#  "username": "root",
#  "password": "root"
#}'
POST http://localhost:1000/api/v1/auth/authenticate
accept: */*
Content-Type: application/json

{
  "username": "root",
  "password": "root"
}

###

# curl -X 'GET'
#  'http://localhost:1000/api/v1/user-info'
#  -H 'accept: */*'
#  -H 'Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJST0xFUyI6IltdIiwic3ViIjoicm9vdCIsImlzcyI6IlBNRSIsImlhdCI6MTY4OTE2MzEwNCwiZXhwIjoxNjg5MTY0MzA0fQ.X5JnTMDsDgi48HaKnf_2_Wkz2vHTEgjuAP1UJ4XFkZY'
GET http://localhost:1000/api/v1/user-info
accept: */*
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJST0xFUyI6IltdIiwic3ViIjoicm9vdCIsImlzcyI6IlBNRSIsImlhdCI6MTY4OTE2MzEwNCwiZXhwIjoxNjg5MTY0MzA0fQ.X5JnTMDsDgi48HaKnf_2_Wkz2vHTEgjuAP1UJ4XFkZY

###





