###
# Create Client
POST http://localhost:2001/v1/api/client/create
accept: application/json
Content-Type: application/json

{
  "clientName": "ema-2",
  "clientSecret": "my-secret",
  "scopes": [
    "admin.read"
  ],
  "clientAuthenticationMethods": [
    "CLIENT_SECRET_BASIC"
  ],
  "authorizationGrantTypes": [
    "AUTHORIZATION_CODE"
  ],
  "redirectUris": [
    "http://localhost:2001/swagger-ui/index.html?continue#/Client/createClient"
  ],
  "postLogoutRedirectUris": [
    "http://localhost:2001/swagger-ui/index.html?continue#/Client/createClient",
    "http://localhost:2001/swagger-ui/index.html?continue#/Client/createClient"
  ],
  "clientSecretExpiresAt": "2023-12-29T08:11:46.715Z"
}

###
# List Clients
GET http://localhost:2001/v1/api/client/list
accept: application/json

###
# Get Clinet by id

GET http://localhost:2001/v1/api/client/1b2c301c-b7e9-431a-b165-3b8ebd22e0c6
accept: application/json

###
# Update client
PATCH http://localhost:2001/v1/api/client/update/0b95dd29-c5d8-4be0-9ed6-37863ce67503
accept: application/json
Content-Type: application/json

{
  "clientName": "ema-2",
  "clientSecret": "my-secret",
  "clientAuthenticationMethods": [
    "CLIENT_SECRET_BASIC"
  ],
  "authorizationGrantTypes": [
    "AUTHORIZATION_CODE"
  ],
  "scopes": [
    "default.read"
  ],
  "redirectUris": [
    "http://localhost:2001/swagger-ui/index.html?continue#/Client/updateClient"
  ],
  "postLogoutRedirectUris": [
    "http://localhost:2001/swagger-ui/index.html?continue#/Client/updateClient"
  ],
  "clientSecretExpiresAt": "2023-12-29T09:22:41.970Z"
}

###
# Delete Client
DELETE http://localhost:2001/v1/api/client/delete/9c375157-9549-4703-8ae0-441f22c965a2
accept: application/json






