###

# curl -X 'GET'
#  'http://localhost:1002/api/account/417725e1-87e0-4f48-ad99-c9c083f1493f/image'
#  -H 'accept: application/octet-stream'
GET http://localhost:1002/api/account/84f11b27-b8d7-4b4a-abe7-82f619b098e3/image
accept: application/octet-stream

###

